CREATE ROLE ubuntu WITH SUPERUSER CREATEROLE LOGIN;
ALTER USER ubuntu WITH CREATEDB;
-- ALTER USER ubuntu WITH PASSWORD 'some_password';

-- PostgREST
CREATE ROLE authenticator NOINHERIT;
CREATE ROLE admins;
CREATE ROLE anonymous;

GRANT anonymous, admins TO authenticator;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO anonymous;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admins;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admins;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admins;

GRANT EXECUTE ON FUNCTION
  register(VARCHAR(255), VARCHAR(255), VARCHAR(128), VARCHAR(18)),
  login(VARCHAR(255), VARCHAR(255))
  TO anonymous;

